_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.6
            "6": 4.45.2
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 128
dataset:
    value: CVPR_2024_dataset
epochs:
    value: 50
